name: Update pnpm-lock.yaml

on:
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Required for pushing changes

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2' # Matches your package.json engines: ">=20.12.2"
          cache: 'pnpm' # Caches pnpm store for faster installs

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3 # Matches your packageManager: "pnpm@9.12.3"
          run_install: false # We'll run pnpm install manually

      - name: Verify pnpm installation
        run: pnpm --version # Confirm pnpm is installed

      - name: Install dependencies and update lockfile
        run: pnpm install --no-frozen-lockfile
        env:
          PNPM_HEADLESS: true # Optional: Faster installs in CI
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }} # Required for your build

      - name: Run build
        run: pnpm run build
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }} # Ensure API key is available

      - name: Commit updated pnpm-lock.yaml
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pnpm-lock.yaml
          if git diff --staged --quiet; then
            echo "No changes to pnpm-lock.yaml"
          else
            git commit -m "chore: update pnpm-lock.yaml [skip ci]"
            git push
          fi
